/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rkeeves_HelloJNI */

#ifndef _Included_com_rkeeves_HelloJNI
#define _Included_com_rkeeves_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_rkeeves_HelloJNI
	 * Method:    sayHello
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_rkeeves_HelloJNI_sayHello
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
